title: "Shrey.Codes"
email: shreycodes@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Shrey 
paginate: 30
disqus: 'shreykavi'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-219224212-1
domain: shreykavi.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://shreykavi.github.io  # the base hostname and protocol for your site, e.g. http://example.com
layout: default
comments: true
formspree: xwkaggaa

# Authors
authors:
  shrey:
    name: Shrey 
    display_name: Shrey
    avatar: 'assets/images/sal.png'
    email: shreykavi@gmail.com
    # web: https://www.wowthemes.net/category/jekyll-themes/
    # twitter: https://twitter.com/shreykavi
    description: ""

# Social
social:
  linkedin: https://www.linkedin.com/in/shreykavi/
  github: https://github.com/shreykavi
  medium: https://shreykavi.medium.com/
  twitter: https://twitter.com/shreycodes
  company_link: https://cleancut.ai/
  # instagram: https://www.instagram.com/bootstrapstarter/
  # facebook: https://www.facebook.com/bootstrapstartercom-346329609045284

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives